version: '3.9'

services:
  netauth.redis:
    image: redis:8.4.0-alpine
    container_name: NetAuth.Redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  netauth.database:
    image: postgres:18-alpine
    container_name: NetAuth.Database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NetAuth
    ports:
      - "5434:5432"
    volumes:
      - postgres_netauth:/var/lib/postgresql

  netauth.seq:
    image: datalust/seq:latest
    container_name: netauth.seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=123456
    restart: unless-stopped
    ports:
      - "5341:5341" # Seq ingestion port
      - "8081:80"   # Seq UI and API
    volumes:
      - seq_data:/data

volumes:
  postgres_netauth:
  seq_data: