version: '3.9'

services:
  netauth.redis:
    image: redis:8.6.1-alpine
    container_name: NetAuth.Redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  netauth.database:
    image: postgres:18-alpine
    container_name: NetAuth.Database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NetAuth
    ports:
      - "5434:5432"
    volumes:
      - postgres_netauth:/var/lib/postgresql

  netauth.seq:
    image: datalust/seq:latest
    container_name: netauth.seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=123456
    restart: unless-stopped
    ports:
      - "5341:5341" # Seq ingestion port
      - "8081:80"   # Seq UI and API
    volumes:
      - seq_data:/data
  
  # Jaeger all-in-one = OTLP receiver (Collector-lite) + Observability backend (Trace storage + query) + UI.
  netauth.jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: netauth.jaeger
    restart: unless-stopped
    ports:
      - "4317:4317" # gRPC - OTLP (OpenTelemetry Protocol) - Primary endpoint for receiving gRPC-based trace data from OpenTelemetry instrumented applications.
      - "16686:16686" # TCP - Jaeger UI - The web interface for viewing and searching traces.

volumes:
  postgres_netauth:
  seq_data: